export const algebraTitles = [
  "Quadratic formula",
  "Cubic Formula",
  "Discriminant",
  "Binominal Theorem",
  "Sum of Arithmetic Series",
  "Sum of Geometric Series",
  "Polynominal Roots",
  "Logarithm Properties",
];
export const statisticsTitles = [
  "Arithmetic Mean",
  "Harmonic Mean",
  "Geometric Mean",
  "Median",
  "Mode",
  "Arithmetic Variance",
  "Geometric Variance",
  "Arithmetic Standard Deviation",
  "Geometric Standard Deviation",
  "Covariance",
  "Correlation Coefficient",
  "Z-score",
  "Regression Line",
  "First Quartil",
  "First Quartil Index",
  "Second Quartil",
  "Second Quartil Index",
  "Third Quartil",
  "Third Quartil Index",
  "Fourth Quartil",
  "Fourth Quartil Index",
  "Interval between Quartils",
  "Upper Whisker",
  "Lower Whisker",
  "Lower Outliers",
  "Upper Outliers",
  "Pearson's Assymetry Index",
  "Person's Correlation Test",
  "Pearson's Test",
];
export const probabilityTitles = [
  "Simple Probability",
  "Addition Rule",
  "Multiplication Rule",
  "Bayes' Theorem",
  "Expected Value",
  "Binominal Distribution",
  "Poisson Distribution",
];
export const combinatoricsTitles = [
  "Factorial",
  "Permutation without Repetition",
  "Permutation of Multisets",
  "Distinct Permutation without Repetition",
  "Distinc Permutation with Repetition",
  "Combination without Repetition",
  "Combination with Repetition",
  "Inclusion-Exclusion Principle",
  "Pascal Triangle",
];
export const trigonometryTitles = [
  "Pythagorean Identity",
  "Sine Rule",
  "Cosine Rule",
  "Tangent Function",
  "Sum of Angles",
  "Difference of Angles",
  "Double Angle (Sine)",
  "Double Angle(Cosine)",
  "Law of Sines",
  "Law of Cosines",
];
