import {
  AlgebraFormulaNamesReg,
  CombinationsTypesReg,
  GeometryFormulaNamesReg,
  StatisticsFormulaNamesReg,
  TrigonometryFormulaNamesReg,
} from "./declarations/types";

export const titlesAlgebra = [
  "Linear Formula",
  "Discriminant",
  "Number of Roots",
  "Quadratic Formula",
  "Cubic Formula",
  "Difference of Squares",
  "Least Common Multiple",
  "Greatest Common Divisor",
  "Common Difference of Arithmetic Series",
  "Sum of Arithmetic Series",
  "Common Difference of Geometric Series",
  "Sum of Geometric Series",
  "Binominal Theorem",
] as AlgebraFormulaNamesReg[];
export const titlesCombinatorics = [
  "Permutation without Repetition",
  "Circular Permutation",
  "Multiset Permutation",
  "Distinct Permutation without Repetition",
  "Distinct Permutation with Repetition",
  "Combination without Repetition",
  "Combination with Repetition",
] as CombinationsTypesReg[];
export const titlesStatistics = [
  "Arithmetic Mean",
  "Harmonic Mean",
  "Geometric Mean",
  "Median",
  "Mode",
  "Arithmetic Variance",
  "Geometric Variance",
  "Covariance",
  "Arithmetic Standard Deviation",
  "Geometric Standard Deviation",
  "Coefficient of Correlation",
  "Z-score",
  "Regression Line",
  "First Quartil",
  "First Quartil Index",
  "Second Quartil",
  "Second Quartil Index",
  "Third Quartil",
  "Third Quartil Index",
  "Fourth Quartil",
  "Fourth Quartil Index",
  "Interval between Quartils",
  "Upper Whisker",
  "Lower Whisker",
  "Lower Outliers",
  "Upper Outliers",
  "Pearson's Assymetry Index",
  "Person's Correlation Test",
  "Pearson's Test",
] as StatisticsFormulaNamesReg[];
export const titlesProbability = [
  "Simple Probability",
  "Addition Rule",
  "Multiplication Rule",
  "Bayes' Theorem",
  "Expected Value",
  "Binominal Distribution",
  "Poisson Distribution",
];
export const titlesTrigonometry = [
  "Sine",
  "Cosine",
  "Tangent",
  "Secant",
  "Cosecant",
  "Cotangent",
  "Sine Angle",
  "Cosine Angle",
  "Tangent Angle",
  "Hyperbolic Sine",
  "Hyperbolic Cosine",
  "Hyperbolic Tangent",
  "Angle Of Hyperbolic Sine",
  "Angle Of Hyperbolic Cosine",
  "Angle Of Hyperbolic Tangent",
  "Point Of Tangent Angle",
  "Hypotenuse",
  "Triangle Legs",
  "Sine As Cofunction",
  "Cosine As Cofunction",
  "Tangent As Cofunction",
  "Secant As Cofunction",
  "Cotangent As Cofunction",
  "Sine With Pythagorean Identity",
  "Cosine With Pythagorean Identity",
  "Tangent With Pythagorean Identity",
  "Secant With Pythagorean Identity",
  "Cotangent With Pythagorean Identity",
  "Cosecant With Pythagorean Identity",
  "Law Of Sines",
  "Law Of Cosines",
  "Halved Angled Sine",
  "Halved Angled Cosine",
  "Halved Angle Tangent",
  "Double Angled Sine",
  "Double Angled Cosine",
  "Double Angled Tangent",
  "Triple Angled Sine",
  "Triple Angled Cosine",
  "Triple Angled Tangent",
  "Sine For United Angles",
  "Sine For Added Angles",
  "Sine For Subtracted Angles",
  "Cosine For United Angles",
  "Cosine For Added Angles",
  "Cosine For Subtracted Angles",
  "Tangent For United Angles",
  "Tangent For Added Angles",
  "Tangent For Subtracted Angles",
] as TrigonometryFormulaNamesReg[];
export const titlesGeometry = [
  "Triangle Area",
  "Triangle Perimeter",
  "Rectangle Area",
  "Rectangle Perimeter",
  "Trapezoid Area",
  "Trapezoid Perimeter",
  "Parallelogram Area",
  "Parallelogram Perimeter",
  "Ellipsis Area",
  "Ellipsis Perimeter",
  "Circle Area",
  "Circle Perimeter",
  "Circle Ring",
  "Circle Sector Area",
  "Circle Sector Length",
  "Triangular Pyramid Area",
  "Triangular Pyramid Volume",
  "Square Pyramid Area",
  "Square Pyramid Volume",
  "Cone Area",
  "Cone Volume",
  "Cone of Frustum Area",
  "Cone of Frustum Volume",
  "Cuboid Area",
  "Cuboid Volume",
  "Cube Area",
  "Cube Volume",
  "Prism Area",
  "Prism Volume",
  "Sphere Area",
  "Sphere Volume",
  "Torus Area",
  "Torus Volume",
] as GeometryFormulaNamesReg[];
export const first50Primes = [
  2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71,
  73, 79, 83, 89, 97, 101, 103, 107, 109, 113, 127, 131, 137, 139, 149, 151,
  157, 163, 167, 173, 179, 181, 191, 193, 197, 199, 211, 223, 227, 229,
];
