export const titlesAlgebra = [
  "Linear Formula",
  "Discriminant",
  "Number of Roots",
  "Quadratic Formula",
  "Cubic Formula",
  "Difference of Squares",
  "Least Common Multiple",
  "Greatest Common Divisor",
  "Common Difference of Arithmetic Series",
  "Sum of Arithmetic Series",
  "Common Difference of Geometric Series",
  "Sum of Geometric Series",
  "Binominal Theorem",
];
export const titlesCombinatorics = [
  "Permutation without Repetition",
  "Circular Permutation",
  "Multiset Permutation",
  "Distinct Permutation without Repetition",
  "Distinct Permutation with Repetition",
  "Combination without Repetition",
  "Combination with Repetition",
];
export const titlesStatistics = [
  "Arithmetic Mean",
  "Harmonic Mean",
  "Geometric Mean",
  "Median",
  "Mode",
  "Arithmetic Variance",
  "Geometric Variance",
  "Covariance",
  "Arithmetic Standard Deviation",
  "Geometric Standard Deviation",
  "Coefficient of Correlation",
  "Z-score",
  "Regression Line",
  "First Quartil",
  "First Quartil Index",
  "Second Quartil",
  "Second Quartil Index",
  "Third Quartil",
  "Third Quartil Index",
  "Fourth Quartil",
  "Fourth Quartil Index",
  "Interval between Quartils",
  "Upper Whisker",
  "Lower Whisker",
  "Lower Outliers",
  "Upper Outliers",
  "Pearson's Assymetry Index",
  "Person's Correlation Test",
  "Pearson's Test",
];
export const titlesProbability = [
  "Simple Probability",
  "Addition Rule",
  "Multiplication Rule",
  "Bayes' Theorem",
  "Expected Value",
  "Binominal Distribution",
  "Poisson Distribution",
];
export const titlesTrigonometry = [
  "Pythagorean Identity",
  "Sine Rule",
  "Cosine Rule",
  "Tangent Function",
  "Sum of Angles",
  "Difference of Angles",
  "Double Angle (Sine)",
  "Double Angle(Cosine)",
  "Law of Sines",
  "Law of Cosines",
];
export const titlesGeometry = ["Square Area", "Square Volume"];
export const first50Primes = [
  2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71,
  73, 79, 83, 89, 97, 101, 103, 107, 109, 113, 127, 131, 137, 139, 149, 151,
  157, 163, 167, 173, 179, 181, 191, 193, 197, 199, 211, 223, 227, 229,
];
